#!/usr/bin/env python3
"""
progress_tracker.py — Dopamine progress tracker for HYPER-SILLs.

Turns dry usage data into visible momentum: skills used, categories explored,
day streak, and unlocked achievements. Reads the .skill-memory learning loop and
writes a snapshot to progress-tracker.yaml.

    python scripts/progress_tracker.py        # print progress + write snapshot

Pairs with the BROski XP path (sills_broski_xp_reward.py already mints XP on
activity) — this surfaces the momentum. No external deps.
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
USAGE_LOG = ROOT / ".skill-memory" / "usage-log.jsonl"
REGISTRY_PATH = ROOT / "skills-registry.json"
SNAPSHOT = ROOT / "progress-tracker.yaml"

# Achievement definitions: (id, label, description, predicate(stats) -> bool)
ACHIEVEMENTS = [
    ("first_skill",   "🌱 First Spark",       "Used your first skill",            lambda s: s["total_used"] >= 1),
    ("ten_skills",    "🔥 Getting Warm",      "Used 10 distinct skills",          lambda s: s["distinct"] >= 10),
    ("plugin_pioneer","🏗️ Plugin Pioneer",    "Used PLUGIN FORGE (HS-128)",        lambda s: "HS-128" in s["used_ids"]),
    ("distributor",   "🚢 Distributor",       "Used a distribution skill (128-130)", lambda s: bool(s["used_ids"] & {"HS-128","HS-129","HS-130"})),
    ("explorer",      "🧭 Explorer",          "Touched skills in 3+ categories",   lambda s: len(s["categories"]) >= 3),
    ("streak_3",      "📅 Three-Day Streak",  "Active 3 different days",            lambda s: s["active_days"] >= 3),
    ("half_century",  "💯 Half-Century",      "Used 50 distinct skills",           lambda s: s["distinct"] >= 50),
]


def _events() -> list[dict]:
    if not USAGE_LOG.exists():
        return []
    out = []
    for line in USAGE_LOG.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return out


def _category_of(reg: dict) -> dict:
    return {s["id"].upper(): s.get("category", "").lower().rstrip("/") for s in reg.get("skills", [])}


def compute() -> dict:
    events = _events()
    reg = json.loads(REGISTRY_PATH.read_text(encoding="utf-8")) if REGISTRY_PATH.exists() else {"skills": []}
    cat_of = _category_of(reg)

    used = Counter()
    days = set()
    categories = set()
    for e in events:
        for sid in e.get("skills", []):
            sid = sid.upper()
            used[sid] += 1
            if sid in cat_of:
                categories.add(cat_of[sid])
        ts = e.get("ts", "")
        if ts:
            days.add(ts[:10])

    stats = {
        "total_used": sum(used.values()),
        "distinct": len(used),
        "used_ids": set(used),
        "categories": categories,
        "active_days": len(days),
        "vault_size": len(reg.get("skills", [])),
    }
    unlocked = [(aid, label, desc) for aid, label, desc, pred in ACHIEVEMENTS if pred(stats)]
    locked = [(aid, label, desc) for aid, label, desc, pred in ACHIEVEMENTS if not pred(stats)]
    stats["unlocked"] = unlocked
    stats["locked"] = locked
    stats["top"] = used.most_common(5)
    return stats


def _write_snapshot(s: dict) -> None:
    lines = [
        "# HYPER-SILLs progress snapshot (generated by progress_tracker.py)",
        f"generated: {datetime.now().isoformat(timespec='seconds')}",
        "stats:",
        f"  skills_used_total: {s['total_used']}",
        f"  distinct_skills: {s['distinct']}",
        f"  of_vault: {s['vault_size']}",
        f"  categories_explored: {len(s['categories'])}",
        f"  active_days: {s['active_days']}",
        "achievements_unlocked:",
    ]
    for aid, label, _ in s["unlocked"]:
        lines.append(f"  - {aid}  # {label}")
    if not s["unlocked"]:
        lines.append("  []")
    SNAPSHOT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render(s: dict) -> str:
    pct = (s["distinct"] / s["vault_size"] * 100) if s["vault_size"] else 0
    filled = int(pct // 5)
    bar = "█" * filled + "░" * (20 - filled)
    out = [
        "\n🏆 HYPER-SILLs Progress",
        "─" * 40,
        f"  Skills explored: {s['distinct']}/{s['vault_size']}  [{bar}] {pct:.0f}%",
        f"  Total uses: {s['total_used']}   Categories: {len(s['categories'])}   Streak days: {s['active_days']}",
        "",
        f"  ✨ Unlocked ({len(s['unlocked'])}/{len(ACHIEVEMENTS)}):",
    ]
    for _, label, desc in s["unlocked"]:
        out.append(f"     {label} — {desc}")
    if s["locked"]:
        nxt = s["locked"][0]
        out.append(f"\n  🔒 Next up: {nxt[1]} — {nxt[2]}")
    if not s["total_used"]:
        out.append("\n  No usage yet — use a skill and it shows up here. No pressure. 🐕")
    out.append("")
    return "\n".join(out)


def main() -> int:
    s = compute()
    _write_snapshot(s)
    print(render(s))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
